// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package processor

import (
	"github.com/margostino/anfield/configuration"
	"github.com/margostino/anfield/db"
	"github.com/margostino/anfield/kafka"
	"github.com/margostino/anfield/scrapper"
)

// Injectors from wire.go:

func NewApp() (*App, error) {
	configurationConfiguration := configuration.GetConfig()
	kafkaParams := kafka.NewKafkaParams(configurationConfiguration)
	writer := kafka.NewWriter(kafkaParams)
	database := db.NewDBConnection()
	scrapperScrapper := scrapper.New()
	channels := NewChannels()
	syncMap := NewWaitGroups()
	logger := NewLogger(configurationConfiguration)
	app := &App{
		kafka:         writer,
		db:            database,
		scrapper:      scrapperScrapper,
		configuration: configurationConfiguration,
		channels:      channels,
		waitGroups:    syncMap,
		logger:        logger,
	}
	return app, nil
}
