// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package db

import (
	"github.com/margostino/anfield/configuration"
)

// Injectors from wire.go:

func NewDBConnection() *Database {
	configurationConfiguration := configuration.GetConfig()
	options := DefaultConnectionOpt(configurationConfiguration)
	database := Connect(options)
	return database
}
