// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package bot

import (
	"github.com/margostino/anfield/configuration"
	"github.com/margostino/anfield/db"
)

// Injectors from wire.go:

func NewApp() (*App, error) {
	database := db.NewDBConnection()
	v := NewActions(database)
	configurationConfiguration := configuration.GetConfig()
	botAPI := NewBot(configurationConfiguration)
	v2 := NewMessagesBuffer()
	app := &App{
		actions:       v,
		db:            database,
		bot:           botAPI,
		configuration: configurationConfiguration,
		messageBuffer: v2,
	}
	return app, nil
}
