// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package bot

import (
	"github.com/margostino/anfield/configuration"
	"github.com/margostino/anfield/db"
)

// Injectors from wire.go:

func NewApp() (*App, error) {
	configurationConfiguration := configuration.GetConfig()
	botAPI := NewBot(configurationConfiguration)
	database := db.NewDBConnection()
	v := NewChannel()
	app := &App{
		bot:           botAPI,
		db:            database,
		configuration: configurationConfiguration,
		subscriptions: v,
	}
	return app, nil
}
